#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

# Store current environment so that scripts can access it if needed.
touch /dev/shm/cron-environment
chmod 600 /dev/shm/cron-environment
export > /dev/shm/cron-environment

exec /usr/sbin/cron -f
