#!/bin/bash -e

# Store current environment so that scripts can access it if needed.
touch /dev/shm/cron-environment
chmod 600 /dev/shm/cron-environment
export > /dev/shm/cron-environment

exec /usr/sbin/cron -f 2>&1
